package helper

var (
	// InternalServer ...
	InternalServer = "internal_server"
	// JWT ...
	JWT = "jwt"
	// InvalidEmail ...
	InvalidEmail = "invalid_email"
	// InvalidCredential ...
	InvalidCredential = "invalid_credential"
	// UnexpectedClaims ...
	UnexpectedClaims = "unexpected_claims"
	// ExpiredToken ...
	ExpiredToken = "expired_token"
	// DuplicateEmail ...
	DuplicateEmail = "duplicate_email"
)
